name: masworld
version: '1.15.9'
main: com.mas6y6.masworld.Masworld
api-version: '1.21'
description: Masworld SMP Custom Item Handler Plugin
bootstrapper: com.mas6y6.masworld.MasworldPluginBootstrap
dependencies:
  server:
    NBTAPI:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      load: BEFORE
      required: true
      join-classpath: true
permissions:
  masworld.fixitems:
    description: Allows the player to fix items with NBT
    default: op

  masworld.admin:
    description: Allows the player to use admin commands
    default: op

  masworld.itemeffects:
    description: Allow the player to use the ItemEffects system
    default-permission: true

  masworld.itemeffects.debug:
    description: Allows the player to use the debug commands
    default: op

  masworld.debug:
    description: Add CustomModelData to item
    default: op

  masworld.itemeffects.editor:
    description: Allows you to make EffectRegisteries
    default: op

  masworld.adminstick:
    description: I want admin stick
    default: op